import { Inter } from "next/font/google";
import type { Metadata } from "next";

import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

import { cn } from "@/lib/utils";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GKJ Slogohimo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full" style={{ scrollBehavior: "smooth" }}>
        <body
          className={cn(
            "relative h-full font-sans antialiased",
            inter.className
          )}
        >
          <Toaster position="top-right" richColors />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
